[package]
name = "rust_resemble"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]

[lib]
name = "rust_resemble"
path = "./src/lib.rs"

[dependencies]
image = "0.12.3"
num-traits = "0.1.37"
rayon = "0.7.0"