[package]
name = "rust_resemble"
version = "0.2.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

[lib]
name = "rust_resemble"
path = "./src/lib.rs"

[dependencies]
image = "0.22"
num-traits = "0.2"
rayon = "1.3"